// src/app/layout.js أو layout.jsx

import "./globals.css";
import Nav from "./Nav";
import BottomNav from "./(Main)/BottomNav";
import { UserProvider } from "./context/UserContext"; // ✅ استيراد الكونتكست

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* رابط أيقونات FontAwesome */}
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css"
          crossOrigin="anonymous"
          referrerPolicy="no-referrer"
        />
      </head>
      <body className="antialiased">
        <UserProvider>
          <Nav />
          <main className="pb-32">{children}</main>
          <BottomNav />
        </UserProvider>
      </body>
    </html>
  );
}
